In [12]:
# 10부터 20까지의 정수 배열 생성
import numpy as np
arr = np.arange(10, 21)
print('원본', arr)

# 문제 1: 배열의 첫 번째, 세 번째, 마지막 요소 출력
print(arr[[0, 2, -1]])

# 문제 2: 인덱스 2부터 5까지 요소 출력
print(arr[2:6])

# 문제 3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력
print(arr[:6:2])

# 문제 4: 배열의 요소를 역순으로 출력
print(arr[::-1])

원본 [10 11 12 13 14 15 16 17 18 19 20]
[10 12 20]
[12 13 14 15]
[10 12 14]
[20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

# 문제1: (1,2) 위치의 요소 출력
print(matrix[1, 2])

# 문제2: 두 번째 행 전체 출력
print(matrix[1])

# 문제3: 마지막 열 전체 출력
print(matrix[:, -1])

# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출
print(matrix[0:3:2, 1:5:2])

# 문제4의 풀이 1.
print(matrix[0:2, :])
print(matrix[np.ix_([0, 2], [1, 3])])

원본 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[ 3  7 11]
[[ 1  3]
 [ 9 11]]
[[ 1  3]
 [ 9 11]]


In [26]:
arr = np.arange(1, 21)
print('원본', arr)

# 문제1: 5의 배수만 선택하여 출력
print(arr[arr % 5 == 0])

# 문제2: 3보다 크고 15보다 작은 요소 선택
print(arr[(arr > 3) & (arr < 15)])

# 문제3: 7의 배수이거나 홀수인 요소 선택
print(arr[(arr % 7 == 0) | (arr % 2 == 1)])

원본 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5 10 15 20]
[ 4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13 14 15 17 19]


In [ ]:
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)

# 문제4: 10보다 큰 요소만 100으로 변경
matrix[matrix > 10] = 100
print(matrix)
# 원본이랑 연결된 데이터라는 걸 고려.

원본 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[  1   2   3   4]
 [  5   6   7   8]
 [  9  10 100 100]
 [100 100 100 100]
 [100 100 100 100]]
